allowedLicenses:
  - MIT
  - MIT-0
  - MIT/X11
  - ISC
  - Apache
  - Apache-2.0
  - Apache License 2.0
  - BlueOak-1.0.0
  - BSD
  - BSD-2-Clause
  - BSD-3-Clause
  - 0BSD
  - Python-2.0
  - CC-BY-3.0
  - CC-BY-4.0
  - Zlib
  - CC0-1.0
  - LGPL-3.0-or-later
  - MPL-2.0
  - Unlicense
allowedPackages:
  - thirty-two@1.0.2 #MIT
  - require-like@0.1.2 # MIT
  - react-universal-interface@0.6.2 # Unlicense
  - pause@0.0.1 # MIT https://github.com/stream-utils/pause/tree/v0.0.1 (missing License file)
  - fast-shallow-equal@1.0.0 # Unlicense
  - css-value@0.0.1 # MIT on npm, but missing LICENSE file
  - "@browserbasehq/sdk@2.6.0" # Apache-2.0
  - combine-errors@3.0.3 # MIT https://github.com/matthewmueller/combine-errors (missing LICENSE file, but said in README)
